//@version=5
strategy("My Strategy", overlay=true, margin_long=100, margin_short=100)

close14 = ta.sma(close, 14)
close28 = ta.sma(close, 28)

plot(close14, style=plot.style_circles, color=color.green)
plot(close28, style=plot.style_circles, color=color.red)

longCondition = ta.crossover(close14, close28)
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long)

shortCondition = ta.crossunder(close14, close28)
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short)